<?php

namespace Kwaku\LaravelTestMcp\Services;

use Kwaku\LaravelTestMcp\DTOs\ClassAnalysis;
use Kwaku\LaravelTestMcp\DTOs\GeneratedTest;

class TestGenerator
{
    public function generate(ClassAnalysis $analysis, bool $includeComments = true): GeneratedTest
    {
        $testContent = match ($analysis->type) {
            'controller' => $this->generateControllerTest($analysis, $includeComments),
            'model' => $this->generateModelTest($analysis, $includeComments),
            'service', 'repository', 'action' => $this->generateServiceTest($analysis, $includeComments),
            'formrequest' => $this->generateFormRequestTest($analysis, $includeComments),
            'job' => $this->generateJobTest($analysis, $includeComments),
            'middleware' => $this->generateMiddlewareTest($analysis, $includeComments),
            'listener' => $this->generateListenerTest($analysis, $includeComments),
            default => $this->generateGenericTest($analysis, $includeComments),
        };

        $testType = in_array($analysis->type, ['controller', 'middleware']) ? 'feature' : 'unit';
        $testPath = $this->suggestTestPath($analysis, $testType);

        // Generate factory for models
        $factoryContent = null;
        $factoryPath = null;
        if ($analysis->isModel()) {
            $factoryGenerator = app(FactoryGenerator::class);
            $factoryContent = $factoryGenerator->generate($analysis);
            $factoryPath = "database/factories/{$analysis->shortName}Factory.php";
        }

        return new GeneratedTest(
            testContent: $testContent,
            suggestedTestPath: $testPath,
            testType: $testType,
            factoryContent: $factoryContent,
            factoryPath: $factoryPath,
            coverage: $this->determineCoverage($analysis),
            todos: $this->determineTodos($analysis),
        );
    }

    private function generateControllerTest(ClassAnalysis $analysis, bool $includeComments): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';

        if ($includeComments) {
            $lines[] = "// Feature tests for {$analysis->shortName}";
            $lines[] = "// Generated by Laravel Test MCP";
            $lines[] = '';
        }

        $lines[] = "use {$analysis->className};";

        // Add use statements for dependencies
        foreach ($analysis->dependencies as $dep) {
            if (!str_starts_with($dep, 'Illuminate\\')) {
                $lines[] = "use {$dep};";
            }
        }

        $lines[] = '';

        // Check if we have route information
        $routes = $analysis->laravelFeatures['routes'] ?? [];

        if (!empty($routes)) {
            foreach ($routes as $route) {
                $methodName = $route['action'];
                $httpMethods = $route['methods'];
                $uri = $route['uri'];
                $routeName = $route['name'];
                $middleware = $route['middleware'] ?? [];

                $httpMethod = strtolower($httpMethods[0] ?? 'get');
                if ($httpMethod === 'head') {
                    $httpMethod = 'get';
                }

                // Basic endpoint test
                $lines[] = "test('{$methodName} endpoint returns successful response', function () {";

                if (in_array('auth', $middleware) || in_array('auth:sanctum', $middleware) || in_array('auth:api', $middleware)) {
                    $lines[] = "    \$user = \\App\\Models\\User::factory()->create();";
                    $lines[] = '';
                }

                if ($routeName) {
                    $routeCall = "route('{$routeName}')";
                } else {
                    $routeCall = "'/{$uri}'";
                }

                if (in_array('auth', $middleware) || in_array('auth:sanctum', $middleware) || in_array('auth:api', $middleware)) {
                    $lines[] = "    \$response = \$this->actingAs(\$user)->{$httpMethod}({$routeCall});";
                } else {
                    $lines[] = "    \$response = \$this->{$httpMethod}({$routeCall});";
                }

                $lines[] = '';
                $lines[] = '    $response->assertStatus(200);';
                $lines[] = '});';
                $lines[] = '';

                // Auth middleware test
                if (in_array('auth', $middleware) || in_array('auth:sanctum', $middleware)) {
                    $lines[] = "test('{$methodName} requires authentication', function () {";
                    $lines[] = "    \$response = \$this->{$httpMethod}({$routeCall});";
                    $lines[] = '';
                    $lines[] = '    $response->assertStatus(401);';
                    $lines[] = '});';
                    $lines[] = '';
                }
            }
        } else {
            // No routes found, generate basic method tests
            foreach ($analysis->methods as $method) {
                if ($method->name === '__construct') {
                    continue;
                }

                $lines[] = "test('{$method->name} method works correctly', function () {";

                if ($includeComments) {
                    $lines[] = '    // TODO: Set up test data and make HTTP request';
                    $lines[] = '    // Example:';
                    $lines[] = "    // \$response = \$this->get('/your-route');";
                    $lines[] = '    // $response->assertStatus(200);';
                }

                $lines[] = '    expect(true)->toBeTrue(); // Placeholder';
                $lines[] = '});';
                $lines[] = '';
            }
        }

        return implode("\n", $lines);
    }

    private function generateModelTest(ClassAnalysis $analysis, bool $includeComments): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';

        if ($includeComments) {
            $lines[] = "// Unit tests for {$analysis->shortName} model";
            $lines[] = "// Generated by Laravel Test MCP";
            $lines[] = '';
        }

        $lines[] = "use {$analysis->className};";
        $lines[] = '';

        // Basic instantiation test
        $lines[] = "test('{$analysis->shortName} can be instantiated', function () {";
        $lines[] = "    \$model = new {$analysis->shortName}();";
        $lines[] = '';
        $lines[] = "    expect(\$model)->toBeInstanceOf({$analysis->shortName}::class);";
        $lines[] = '});';
        $lines[] = '';

        // Factory test if fillable fields exist
        $fillable = $analysis->laravelFeatures['fillable'] ?? [];
        if (!empty($fillable)) {
            $lines[] = "test('{$analysis->shortName} can be created with factory', function () {";
            $lines[] = "    \$model = {$analysis->shortName}::factory()->create();";
            $lines[] = '';
            $lines[] = "    expect(\$model)->toBeInstanceOf({$analysis->shortName}::class);";
            $lines[] = '    expect($model->id)->not->toBeNull();';
            $lines[] = '});';
            $lines[] = '';
        }

        // Relationship tests
        $relationships = $analysis->laravelFeatures['relationships'] ?? [];
        foreach ($relationships as $relationship) {
            $relName = $relationship['name'];
            $relType = $relationship['type'];

            $lines[] = "test('{$analysis->shortName} has {$relName} relationship', function () {";
            $lines[] = "    \$model = {$analysis->shortName}::factory()->create();";
            $lines[] = '';

            $expectedClass = match ($relType) {
                'hasOne' => 'Illuminate\Database\Eloquent\Relations\HasOne',
                'hasMany' => 'Illuminate\Database\Eloquent\Relations\HasMany',
                'belongsTo' => 'Illuminate\Database\Eloquent\Relations\BelongsTo',
                'belongsToMany' => 'Illuminate\Database\Eloquent\Relations\BelongsToMany',
                'hasOneThrough' => 'Illuminate\Database\Eloquent\Relations\HasOneThrough',
                'hasManyThrough' => 'Illuminate\Database\Eloquent\Relations\HasManyThrough',
                'morphOne' => 'Illuminate\Database\Eloquent\Relations\MorphOne',
                'morphMany' => 'Illuminate\Database\Eloquent\Relations\MorphMany',
                'morphTo' => 'Illuminate\Database\Eloquent\Relations\MorphTo',
                'morphToMany' => 'Illuminate\Database\Eloquent\Relations\MorphToMany',
                default => 'Illuminate\Database\Eloquent\Relations\Relation',
            };

            $lines[] = "    expect(\$model->{$relName}())->toBeInstanceOf(\\{$expectedClass}::class);";
            $lines[] = '});';
            $lines[] = '';
        }

        // Scope tests
        $scopes = $analysis->laravelFeatures['scopes'] ?? [];
        foreach ($scopes as $scope) {
            $lines[] = "test('{$analysis->shortName} {$scope} scope filters correctly', function () {";
            $lines[] = "    // Create test data";
            $lines[] = "    {$analysis->shortName}::factory()->count(3)->create();";
            $lines[] = '';
            $lines[] = "    \$filtered = {$analysis->shortName}::{$scope}()->get();";
            $lines[] = '';
            $lines[] = '    expect($filtered)->toBeInstanceOf(\Illuminate\Database\Eloquent\Collection::class);';

            if ($includeComments) {
                $lines[] = '    // TODO: Add specific assertions for this scope';
            }

            $lines[] = '});';
            $lines[] = '';
        }

        // Accessor tests
        $accessors = $analysis->laravelFeatures['accessors'] ?? [];
        foreach ($accessors as $accessor) {
            $lines[] = "test('{$analysis->shortName} {$accessor} accessor returns expected value', function () {";
            $lines[] = "    \$model = {$analysis->shortName}::factory()->create();";
            $lines[] = '';
            $lines[] = "    \$value = \$model->{$accessor};";
            $lines[] = '';
            $lines[] = '    expect($value)->not->toBeNull();';

            if ($includeComments) {
                $lines[] = '    // TODO: Add specific assertions for this accessor';
            }

            $lines[] = '});';
            $lines[] = '';
        }

        // Mutator tests
        $mutators = $analysis->laravelFeatures['mutators'] ?? [];
        foreach ($mutators as $mutator) {
            $lines[] = "test('{$analysis->shortName} {$mutator} mutator transforms value correctly', function () {";
            $lines[] = "    \$model = new {$analysis->shortName}();";
            $lines[] = '';
            $lines[] = "    \$model->{$mutator} = 'test value';";
            $lines[] = '';

            if ($includeComments) {
                $lines[] = '    // TODO: Assert that the value was transformed correctly';
            }

            $lines[] = '    expect(true)->toBeTrue(); // Placeholder';
            $lines[] = '});';
            $lines[] = '';
        }

        // Cast tests
        $casts = $analysis->laravelFeatures['casts'] ?? [];
        if (!empty($casts)) {
            $lines[] = "test('{$analysis->shortName} has correct casts', function () {";
            $lines[] = "    \$model = new {$analysis->shortName}();";
            $lines[] = '    $casts = $model->getCasts();';
            $lines[] = '';

            foreach ($casts as $field => $castType) {
                $lines[] = "    expect(\$casts)->toHaveKey('{$field}');";
            }

            $lines[] = '});';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function generateServiceTest(ClassAnalysis $analysis, bool $includeComments): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';

        if ($includeComments) {
            $lines[] = "// Unit tests for {$analysis->shortName}";
            $lines[] = "// Generated by Laravel Test MCP";
            $lines[] = '';
        }

        $lines[] = "use {$analysis->className};";

        // Add mock imports for dependencies
        foreach ($analysis->dependencies as $dep) {
            $lines[] = "use {$dep};";
        }

        if (!empty($analysis->dependencies)) {
            $lines[] = 'use Mockery;';
        }

        $lines[] = '';

        // Setup
        $lines[] = 'beforeEach(function () {';

        if (empty($analysis->dependencies)) {
            $lines[] = "    \$this->service = app({$analysis->shortName}::class);";
        } else {
            // Create mocks for dependencies
            foreach ($analysis->dependencies as $i => $dep) {
                $depName = lcfirst(class_basename($dep));
                $lines[] = "    \$this->{$depName}Mock = Mockery::mock({$dep}::class);";
            }

            $lines[] = '';
            $lines[] = "    \$this->service = new {$analysis->shortName}(";

            $depList = [];
            foreach ($analysis->dependencies as $dep) {
                $depName = lcfirst(class_basename($dep));
                $depList[] = "        \$this->{$depName}Mock";
            }

            $lines[] = implode(",\n", $depList);
            $lines[] = '    );';
        }

        $lines[] = '});';
        $lines[] = '';

        // Cleanup
        if (!empty($analysis->dependencies)) {
            $lines[] = 'afterEach(function () {';
            $lines[] = '    Mockery::close();';
            $lines[] = '});';
            $lines[] = '';
        }

        // Test for each public method
        foreach ($analysis->methods as $method) {
            if ($method->name === '__construct') {
                continue;
            }

            $lines[] = "test('{$method->name} works correctly', function () {";

            // Generate parameter setup
            foreach ($method->parameters as $param) {
                $paramValue = $this->generateParameterValue($param);
                $lines[] = "    \${$param['name']} = {$paramValue};";
            }

            if (!empty($method->parameters)) {
                $lines[] = '';
            }

            // Generate method call
            $paramNames = array_map(fn($p) => "\${$p['name']}", $method->parameters);
            $call = "\$this->service->{$method->name}(" . implode(', ', $paramNames) . ')';

            if ($method->returnType && $method->returnType !== 'void') {
                $lines[] = "    \$result = {$call};";
                $lines[] = '';
                $lines[] = '    expect($result)->not->toBeNull();';

                if ($includeComments) {
                    $lines[] = '    // TODO: Add specific assertions for the return value';
                }
            } else {
                $lines[] = "    {$call};";
                $lines[] = '';
                $lines[] = '    expect(true)->toBeTrue(); // Method executed without exception';
            }

            $lines[] = '});';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function generateFormRequestTest(ClassAnalysis $analysis, bool $includeComments): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';

        if ($includeComments) {
            $lines[] = "// Validation tests for {$analysis->shortName}";
            $lines[] = "// Generated by Laravel Test MCP";
            $lines[] = '';
        }

        $lines[] = "use {$analysis->className};";
        $lines[] = 'use Illuminate\Support\Facades\Validator;';
        $lines[] = '';

        $rules = $analysis->laravelFeatures['rules'] ?? [];

        // Test with valid data
        $lines[] = "test('validation passes with valid data', function () {";
        $lines[] = '    $data = [';

        if (!empty($rules)) {
            foreach ($rules as $field => $rule) {
                $sampleValue = $this->generateSampleValueForRule($field, $rule);
                $lines[] = "        '{$field}' => {$sampleValue},";
            }
        } else {
            if ($includeComments) {
                $lines[] = '        // TODO: Add valid test data';
            }
        }

        $lines[] = '    ];';
        $lines[] = '';
        $lines[] = "    \$request = new {$analysis->shortName}();";
        $lines[] = '    $validator = Validator::make($data, $request->rules());';
        $lines[] = '';
        $lines[] = '    expect($validator->passes())->toBeTrue();';
        $lines[] = '});';
        $lines[] = '';

        // Test required fields
        foreach ($rules as $field => $rule) {
            $ruleStr = is_array($rule) ? implode('|', $rule) : $rule;

            if (str_contains($ruleStr, 'required')) {
                $lines[] = "test('validation fails when {$field} is missing', function () {";
                $lines[] = '    $data = [';

                foreach ($rules as $f => $r) {
                    if ($f !== $field) {
                        $sampleValue = $this->generateSampleValueForRule($f, $r);
                        $lines[] = "        '{$f}' => {$sampleValue},";
                    }
                }

                $lines[] = '    ];';
                $lines[] = '';
                $lines[] = "    \$request = new {$analysis->shortName}();";
                $lines[] = '    $validator = Validator::make($data, $request->rules());';
                $lines[] = '';
                $lines[] = '    expect($validator->fails())->toBeTrue();';
                $lines[] = "    expect(\$validator->errors()->has('{$field}'))->toBeTrue();";
                $lines[] = '});';
                $lines[] = '';
            }
        }

        // Authorization test if applicable
        if ($analysis->laravelFeatures['hasAuthorize'] ?? false) {
            $lines[] = "test('authorization check works correctly', function () {";
            $lines[] = "    \$request = new {$analysis->shortName}();";
            $lines[] = '';

            if ($includeComments) {
                $lines[] = '    // TODO: Set up user and test authorization';
                $lines[] = '    // $this->actingAs($user);';
            }

            $lines[] = '    expect(true)->toBeTrue(); // Placeholder';
            $lines[] = '});';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function generateJobTest(ClassAnalysis $analysis, bool $includeComments): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';

        if ($includeComments) {
            $lines[] = "// Unit tests for {$analysis->shortName} job";
            $lines[] = "// Generated by Laravel Test MCP";
            $lines[] = '';
        }

        $lines[] = "use {$analysis->className};";
        $lines[] = 'use Illuminate\Support\Facades\Bus;';
        $lines[] = 'use Illuminate\Support\Facades\Queue;';
        $lines[] = '';

        // Dispatch test
        $lines[] = "test('{$analysis->shortName} can be dispatched', function () {";
        $lines[] = '    Bus::fake();';
        $lines[] = '';
        $lines[] = "    {$analysis->shortName}::dispatch();";
        $lines[] = '';
        $lines[] = "    Bus::assertDispatched({$analysis->shortName}::class);";
        $lines[] = '});';
        $lines[] = '';

        // Queue test if queueable
        if ($analysis->laravelFeatures['isQueueable'] ?? false) {
            $lines[] = "test('{$analysis->shortName} is pushed to queue', function () {";
            $lines[] = '    Queue::fake();';
            $lines[] = '';
            $lines[] = "    {$analysis->shortName}::dispatch();";
            $lines[] = '';
            $lines[] = "    Queue::assertPushed({$analysis->shortName}::class);";
            $lines[] = '});';
            $lines[] = '';
        }

        // Handle test
        if ($analysis->laravelFeatures['hasHandle'] ?? false) {
            $lines[] = "test('{$analysis->shortName} handle method executes correctly', function () {";

            // Find constructor parameters
            $constructorParams = [];
            foreach ($analysis->methods as $method) {
                if ($method->name === '__construct') {
                    $constructorParams = $method->parameters;
                    break;
                }
            }

            if (!empty($constructorParams)) {
                foreach ($constructorParams as $param) {
                    $paramValue = $this->generateParameterValue($param);
                    $lines[] = "    \${$param['name']} = {$paramValue};";
                }
                $lines[] = '';

                $paramNames = array_map(fn($p) => "\${$p['name']}", $constructorParams);
                $lines[] = "    \$job = new {$analysis->shortName}(" . implode(', ', $paramNames) . ');';
            } else {
                $lines[] = "    \$job = new {$analysis->shortName}();";
            }

            $lines[] = '';

            if ($includeComments) {
                $lines[] = '    // TODO: Mock any dependencies injected into handle()';
            }

            $lines[] = '    $job->handle();';
            $lines[] = '';
            $lines[] = '    expect(true)->toBeTrue(); // Job executed without exception';

            if ($includeComments) {
                $lines[] = '    // TODO: Add assertions for expected side effects';
            }

            $lines[] = '});';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function generateMiddlewareTest(ClassAnalysis $analysis, bool $includeComments): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';

        if ($includeComments) {
            $lines[] = "// Feature tests for {$analysis->shortName} middleware";
            $lines[] = "// Generated by Laravel Test MCP";
            $lines[] = '';
        }

        $lines[] = "use {$analysis->className};";
        $lines[] = 'use Illuminate\Http\Request;';
        $lines[] = 'use Illuminate\Http\Response;';
        $lines[] = '';

        // Basic pass-through test
        $lines[] = "test('{$analysis->shortName} allows valid requests', function () {";
        $lines[] = "    \$request = Request::create('/test', 'GET');";
        $lines[] = "    \$middleware = new {$analysis->shortName}();";
        $lines[] = '';
        $lines[] = '    $response = $middleware->handle($request, function ($req) {';
        $lines[] = "        return new Response('OK');";
        $lines[] = '    });';
        $lines[] = '';
        $lines[] = "    expect(\$response->getContent())->toBe('OK');";
        $lines[] = '});';
        $lines[] = '';

        // Rejection test
        $lines[] = "test('{$analysis->shortName} blocks invalid requests', function () {";

        if ($includeComments) {
            $lines[] = '    // TODO: Set up a request that should be blocked';
        }

        $lines[] = "    \$request = Request::create('/test', 'GET');";
        $lines[] = "    \$middleware = new {$analysis->shortName}();";
        $lines[] = '';
        $lines[] = '    $response = $middleware->handle($request, function ($req) {';
        $lines[] = "        return new Response('OK');";
        $lines[] = '    });';
        $lines[] = '';

        if ($includeComments) {
            $lines[] = '    // TODO: Assert rejection (redirect, 403, etc.)';
        }

        $lines[] = '    expect(true)->toBeTrue(); // Placeholder';
        $lines[] = '});';
        $lines[] = '';

        // Terminate test if applicable
        if ($analysis->laravelFeatures['hasTerminate'] ?? false) {
            $lines[] = "test('{$analysis->shortName} terminate method executes', function () {";
            $lines[] = "    \$request = Request::create('/test', 'GET');";
            $lines[] = "    \$response = new Response('OK');";
            $lines[] = "    \$middleware = new {$analysis->shortName}();";
            $lines[] = '';
            $lines[] = '    $middleware->terminate($request, $response);';
            $lines[] = '';
            $lines[] = '    expect(true)->toBeTrue(); // Terminate executed without exception';
            $lines[] = '});';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function generateListenerTest(ClassAnalysis $analysis, bool $includeComments): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';

        if ($includeComments) {
            $lines[] = "// Unit tests for {$analysis->shortName} listener";
            $lines[] = "// Generated by Laravel Test MCP";
            $lines[] = '';
        }

        $lines[] = "use {$analysis->className};";
        $lines[] = 'use Illuminate\Support\Facades\Event;';
        $lines[] = '';

        // Handle test
        $lines[] = "test('{$analysis->shortName} handles event correctly', function () {";

        if ($includeComments) {
            $lines[] = '    // TODO: Create the event that this listener handles';
            $lines[] = '    // $event = new YourEvent($data);';
        }

        $lines[] = "    \$listener = new {$analysis->shortName}();";
        $lines[] = '';

        if ($includeComments) {
            $lines[] = '    // $listener->handle($event);';
            $lines[] = '    // TODO: Assert expected side effects';
        }

        $lines[] = '    expect(true)->toBeTrue(); // Placeholder';
        $lines[] = '});';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function generateGenericTest(ClassAnalysis $analysis, bool $includeComments): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';

        if ($includeComments) {
            $lines[] = "// Unit tests for {$analysis->shortName}";
            $lines[] = "// Generated by Laravel Test MCP";
            $lines[] = '';
        }

        $lines[] = "use {$analysis->className};";
        $lines[] = '';

        // Basic instantiation test
        $lines[] = "test('{$analysis->shortName} can be instantiated', function () {";

        if (empty($analysis->dependencies)) {
            $lines[] = "    \$instance = new {$analysis->shortName}();";
        } else {
            $lines[] = "    \$instance = app({$analysis->shortName}::class);";
        }

        $lines[] = '';
        $lines[] = "    expect(\$instance)->toBeInstanceOf({$analysis->shortName}::class);";
        $lines[] = '});';
        $lines[] = '';

        // Test each public method
        foreach ($analysis->methods as $method) {
            if ($method->name === '__construct') {
                continue;
            }

            $lines[] = "test('{$method->name} works correctly', function () {";

            if (empty($analysis->dependencies)) {
                $lines[] = "    \$instance = new {$analysis->shortName}();";
            } else {
                $lines[] = "    \$instance = app({$analysis->shortName}::class);";
            }

            $lines[] = '';

            if ($includeComments) {
                $lines[] = '    // TODO: Add test implementation';
            }

            $lines[] = '    expect(true)->toBeTrue(); // Placeholder';
            $lines[] = '});';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function suggestTestPath(ClassAnalysis $analysis, string $testType): string
    {
        $basePath = $testType === 'feature' ? 'tests/Feature' : 'tests/Unit';

        // Mirror the source path structure
        $relativePath = '';
        if (str_contains($analysis->filePath, 'app/')) {
            $relativePath = preg_replace('/^.*app\//', '', $analysis->filePath);
            $relativePath = dirname($relativePath);
            if ($relativePath !== '.') {
                $basePath .= '/' . $relativePath;
            }
        }

        return "{$basePath}/{$analysis->shortName}Test.php";
    }

    /**
     * @return array<string>
     */
    private function determineCoverage(ClassAnalysis $analysis): array
    {
        $coverage = [];

        foreach ($analysis->methods as $method) {
            if ($method->name !== '__construct') {
                $coverage[] = "{$method->name}()";
            }
        }

        if ($analysis->isModel()) {
            foreach ($analysis->laravelFeatures['relationships'] ?? [] as $rel) {
                $coverage[] = "Relationship: {$rel['name']}";
            }
            foreach ($analysis->laravelFeatures['scopes'] ?? [] as $scope) {
                $coverage[] = "Scope: {$scope}";
            }
        }

        return $coverage;
    }

    /**
     * @return array<string>
     */
    private function determineTodos(ClassAnalysis $analysis): array
    {
        $todos = [];

        if ($analysis->isModel() && empty($analysis->laravelFeatures['fillable'])) {
            $todos[] = 'Create factory for this model';
        }

        if ($analysis->isController() && empty($analysis->laravelFeatures['routes'])) {
            $todos[] = 'Register routes for this controller';
        }

        if (!empty($analysis->dependencies)) {
            $todos[] = 'Review mocked dependencies and add specific expectations';
        }

        $todos[] = 'Replace placeholder assertions with actual test logic';
        $todos[] = 'Add edge case tests';

        return $todos;
    }

    /**
     * @param array{name: string, type: ?string, nullable: bool, hasDefault: bool, default: mixed} $param
     */
    private function generateParameterValue(array $param): string
    {
        if ($param['hasDefault'] && $param['default'] !== null) {
            return var_export($param['default'], true);
        }

        return match ($param['type']) {
            'string' => "'test'",
            'int', 'integer' => '1',
            'float', 'double' => '1.0',
            'bool', 'boolean' => 'true',
            'array' => '[]',
            'null' => 'null',
            default => $param['nullable'] ? 'null' : "'test'",
        };
    }

    /**
     * @param string|array $rule
     */
    private function generateSampleValueForRule(string $field, $rule): string
    {
        $ruleStr = is_array($rule) ? implode('|', $rule) : $rule;

        // Check for common field names
        if (str_contains($field, 'email')) {
            return "'test@example.com'";
        }
        if (str_contains($field, 'password')) {
            return "'password123'";
        }
        if (str_contains($field, 'name')) {
            return "'Test Name'";
        }
        if (str_contains($field, 'phone')) {
            return "'1234567890'";
        }
        if (str_contains($field, 'url') || str_contains($field, 'link')) {
            return "'https://example.com'";
        }

        // Check rule types
        if (str_contains($ruleStr, 'integer') || str_contains($ruleStr, 'numeric')) {
            return '1';
        }
        if (str_contains($ruleStr, 'boolean')) {
            return 'true';
        }
        if (str_contains($ruleStr, 'array')) {
            return '[]';
        }
        if (str_contains($ruleStr, 'date')) {
            return "'2024-01-01'";
        }

        return "'test value'";
    }
}
